name: testing_examples
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  clock: 1.1.1
  cloud_firestore: 4.14.0
  cupertino_icons: 1.0.2
  dartx: 1.2.0
  dio: 5.4.0
  flutter:
    sdk: flutter
  freezed_annotation: 2.4.1
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  shared_preferences: 2.2.2

dev_dependencies:
  build_runner: 2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.4.1
  isar_generator: 3.1.0+1
  mocktail: 1.0.3

flutter:
  uses-material-design: true
